module.exports={
	entry:'./public/js/main.js',
	output:{
		path:'./public/js',
		filename:'build.js'
	},
	module:{
	loaders:[
	{
		test:/.vue$/,
		loader:'vue'
	},{
		test:/.js$/,
		exclude:/node_modules/,
		loader:'babel'
	}]
	},
	babel:{
		presets:['es2015'],
		plugins:['transform-runtime']
	}
};